---
# MENU
drinks: DRINKS
appetizers: APPETIZERS
dishes: DISHES

# CONFIGURATION
name: Avra
subtitle: Greek Cuisine & More
logo: 
  light: assets/img/avra.white.png
  dark: assets/img/avra.black.png
  log_alt_text:
    en: "Avra Greek Cuisine Coffee and Cocktails"
    gr: "Αύρα Ελληνική Κουζίνα Καφές και Κοκτέιλς"
hero:
  bg_img: assets/img/hero_bg.jpg

# CONTACT
contact:
  address: 
  - Egremni Rd,Lefkada 310 82, GR
  telephones:
  - +30 2645 033307
  - +30 2645 XXXXXX
  email:
  - info@picnicbistro.ro
  map:
    lat: 38.65496531962637
    lon: 20.565286404346732
    google_map_embed_url: https://www.google.com/maps/embed?pb=!1m14!1m8!1m3!1d1316.4816244066549!2d20.565286!3d38.65484!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x135db15907124da1%3A0xe58fdadd01991f7f!2sAvra%20greek%20cuisine%20%26%20more!5e1!3m2!1sen!2sgr!4v1694469985257!5m2!1sen!2sgr

# SOCIAL
social:
  instagram: URL:instagram
  facebook: URL:facebook
  soundcloud: URL:soundcloud

# REVIEW
review:
  resengo: URL:resengo
  yelp: URL:yelp
  tripadvisor: URL:tripadvisor

# SPECIAL PAGES:
special_pages:
- Privacy Policy
- Cookies
- GDPR

# NAVIGATION
navigation:
- label: Menu
  URL: menu
- label: Reservations
  URL: reservations
- label: Contact
  URL: contact

# OPENING HOURS
opening_hours:
- day: Monday
  hours: 11-23
- day: Tuesday
  hours: 11-23
- day: Wednesday
  hours: 11-18
- day: Thursday
  hours: 11-23
- day: Friday
  hours: 11-22

# RESERVATIONS
reservations:
  telephones: 
  - +40 742 742 642
  emails:
  - info@picnicbistro.ro
  info: |
    The terrace is structured on tables for 3/6 people
    Reservations are made as soon as possible, one day or 3 days in advance, for groups larger than 6 people.
    Reservations are kept for 20 min